### ISSUE TITLE
README formatting

### ISSUE THREAD

**Issue by matburnham** [KevWal/ESP32-Cam-Pico-Project#1]
Looks like the README could do with better markdown formatting, or not actually having a Markdown extension so that it doesn't get formatted a Markdown.

e.g. the Power Consumption section is a tad difficult to read when GitHub renders the Markdown:
`
ESP32 Cam module, regulator removed and flash LED transistor removed 44ma - Default frequency 14ma - Reduce to 20Mhz 14ma - Turn off BT & WIFI 16ma - Post SPI / Lora Setup 42ma - Camera setup 38ma - Disable camera XCLK 15ma - Turn off camera
`

The raw file is much more readable:
```
ESP32 Cam module, regulator removed and flash LED transistor removed
	44ma - Default frequency
	14ma - Reduce to 20Mhz
	14ma - Turn off BT & WIFI
	16ma - Post SPI / Lora Setup
	42ma - Camera setup
	38ma - Disable camera XCLK
	15ma - Turn off camera
```

**Comment by KevWal** [comment]
Mostly sorted!
